<paste log output from Kubernetes-mediated prediction, here>
(.python3.7devops) (base) Patricks-MacBook-Pro-4:project-ml-microservice-kubernetes patson$ ./run_kubernetes.sh 
Error from server (AlreadyExists): pods "flask-ml-devops" already exists
NAME              READY   STATUS    RESTARTS   AGE
flask-ml-devops   1/1     Running   0          14m
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000